name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.0.6
author: Aleksander Woźniak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #flutter_icons: ^1.1.0
  intl: ^0.18.1
  material: ^1.0.0+2
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
